allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': false
  esbuild: false
  prisma: false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - generative-ui-kit@0.1.0
